### ISSUE TITLE
Slide 5 or whatever number slides at a time ?

### ISSUE THREAD

**Issue by ghost** [risq/jquery-advanced-news-ticker#3]
Is there a way to slide 5 news at a time instead of one at a time? 

Thanks

**Comment by ghost** [comment]
Anyone?

**Comment by risq** [comment]
For the moment you can't really do that without modifying the plugin sources, but I'll try to implement that in the next release. Sorry !

**Comment by ghost** [comment]
oh okay well thanks for your response :)
