### ISSUE TITLE
How to make that when it's scrolling it will scroll smooth up ?

### ISSUE THREAD

**Issue by Csharper1972** [risq/jquery-advanced-news-ticker#7]
The way it is now it looks like the top line jump over. Seems like the text jump all the time.
Is there anyway to make this jquery to move smooth just scroll up all the time over again the text and not like jumping ?

See what i mean on my site here: http://newsxpressmedia.com/
The effect of the scrolling make it look like it's jumping.

**Comment by risq** [comment]
I don't understand your question : your problem has nothing to do with the plugin. You don't even call it. Please ask to the creator of the plugin you used.
